config/routes.rb
Rails.application.routes.draw do
  # resources :entries, only: [:show]
  resources :plans, only: [:show, :index]
  resources :foods, only: [:show, :index]
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: "plans#index"
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :plan
  belongs_to :food
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, :presence => true
  # has_many :entries, :through => :plans
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :name, :presence => true
  has_many :entries
  has_many :food, :through => :entries
  accepts_nested_attributes_for :entries, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < InheritedResources::Base

  private

    def entry_params
      params.require(:entry).permit(:plan_id, :food_id, :quantity, :default, :hidden)
    end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  # def new
  #   @food = Food.new
  # end

  # GET /foods/1/edit
  # def edit
  # end

  # POST /foods
  # POST /foods.json
  # def create
  #   @food = Food.new(food_params)
  #
  #   respond_to do |format|
  #     if @food.save
  #       format.html { redirect_to @food, notice: 'Food was successfully created.' }
  #       format.json { render :show, status: :created, location: @food }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @food.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  # def update
  #   respond_to do |format|
  #     if @food.update(food_params)
  #       format.html { redirect_to @food, notice: 'Food was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @food }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @food.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /foods/1
  # DELETE /foods/1.json
  # def destroy
  #   @food.destroy
  #   respond_to do |format|
  #     format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :unit_of_measure, :calories)
    end
end

app/controllers/plans_controller.rb
class PlansController <  ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  # def new
  #   @plan = Plan.new
  # end

  # GET /plans/1/edit
  # def edit
  # end

  # POST /plans
  # POST /plans.json
  # def create
  #   @plan = Plan.new(plan_params)
  #
  #   respond_to do |format|
  #     if @plan.save
  #       format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
  #       format.json { render :show, status: :created, location: @plan }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @plan.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  # def update
  #   respond_to do |format|
  #     if @plan.update(plan_params)
  #       format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @plan }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @plan.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /plans/1
  # DELETE /plans/1.json
  # def destroy
  #   @plan.destroy
  #   respond_to do |format|
  #     format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    def plan_params
      params.require(:plan).permit(:name, :calories)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plan_id %>
    <%= form.text_field :plan_id, id: :entry_plan_id %>
  </div>

  <div class="field">
    <%= form.label :food_id %>
    <%= form.text_field :food_id, id: :entry_food_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :entry_quantity %>
  </div>

  <div class="field">
    <%= form.label :default %>
    <%= form.check_box :default, id: :entry_default %>
  </div>

  <div class="field">
    <%= form.label :hidden %>
    <%= form.check_box :hidden, id: :entry_hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Plan</th>
      <th>Food</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.plan %></td>
        <td><%= entry.food %></td>
        <td><%= entry.quantity %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan:</strong>
  <%= @entry.plan %>
</p>

<p>
  <strong>Food:</strong>
  <%= @entry.food %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @entry.quantity %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_name %>
  </div>

  <div class="field">
    <%= form.label :unit_of_measure %>
    <%= form.text_field :unit_of_measure, id: :food_unit_of_measure %>
  </div>

  <div class="field">
    <%= form.label :calories %>
    <%= form.number_field :calories, id: :food_calories %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit of measure</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.unit_of_measure %></td>
        <td><%= food.calories %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%# link_to 'Edit', edit_food_path(food) %></td>
        <td><%# link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Unit of measure:</strong>
  <%= @food.unit_of_measure %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @food.calories %>
</p>

<%# link_to 'Edit', edit_food_path(@food) %> |
<%# link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calories</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :plan_name %>
  </div>

  <div class="field">
    <%= form.label :calories %>
    <%= form.number_field :calories, id: :plan_calories %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= plan.calories %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%# link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%# link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Target:</strong>
  <%= @plan.calories %>
</p>

<p>
  <strong>Calories:</strong>
  <span id="calories">
    -
  </span>
</p>

<table>
  <tr>
    <th></th>
    <th>Food</th>
    <th>Quantity</th>
    <th>Calories</th>
  </tr>
  <% @plan.entries.each do |entry| %>
  <tr class="entry">
    <td><%= check_box_tag 'checked', entry.id, entry.default %></td>
    <td><%= entry.food.name %></td>
    <td style="display:none;" id="calories-per"><%= entry.food.calories %></td>
    <td style="display:none;" id="protein-per"><%= entry.food.protein %></td>
    <td style="display:none;" id="carbs-per"><%= entry.food.carbohydrates %></td>
    <td style="display:none;" id="fat-per"><%= entry.food.fat %></td>
    <td><%= text_field_tag 'quantity', entry.quantity %> <%= entry.food.unit_of_measure %></td>
    <td id="calories">-</td>
  </tr>
  <% end %>
  <tr class="additional-calories">
    <td></td>
    <td>Additional Calories</td>
    <td></td>
    <td><%= text_field_tag 'additional-calories', 0 %></td>
  </tr>
</table>

<%# link_to 'Edit', edit_plan_path(@plan) %> |
<%# link_to 'Back', plans_path %>